### ISSUE TITLE
How would one use this with a binary image?

### ISSUE THREAD

**Issue by adishavit** [mikolalysenko/rectangle-decomposition#1]
Say I have a binary image that I would like to decompose with this lib.
From the interface, it seems that the image (pixels) need to be decomposed into 4-connected contours. Is this correct?  
If so, do you have a recommendation for a library that can do this?

**Comment by mikolalysenko** [comment]
Use this module: https://github.com/mikolalysenko/bitmap-to-boxes

**Comment by adishavit** [comment]
Cool! Thanks :-)

**Comment by adishavit** [comment]
BTW, is there a module for doing this for grayscale image? I.e. segment single color contiguous regions into rectangles.

**Comment by mikolalysenko** [comment]
You could use [ndarray-ops](http://github.com/scijs/ndarray-ops).eq to pull out each level and segment them separately, but nothing right now that works out of the box.

**Comment by adishavit** [comment]
Thanks.
